import * as fs from 'fs';
const defs = require('commands/lib/commands.json');

let ts = `// This file is generated by "yarn build:commands".

// Set of commands that are writable.
export const write = new Set<string>([
`;

const commands = Object.keys(defs);
for (const command of commands) {
  const cmd = command.toUpperCase();
  const def = defs[command];
  const isWritable = Array.isArray(def.flags) && def.flags.includes('write');
  if (isWritable) ts += `  '${cmd}',\n`;
}
ts += `]);
`;

const dir = 'src/generated';
fs.mkdirSync(dir, {recursive: true});
const filename = dir + '/commands.ts';
fs.writeFileSync(filename, ts);
console.log('Wrote', filename);
